[package]
name = "spells"
version = "1.3.6"
authors = ["Andrew-Schwartz <andrewschwartz59@gmail.com>"]
edition = "2021"

[dependencies.iced]
version = "0.4.2"
default-features = false
# for release
features = ["glow", "pure"]
# for debug
#features = ["glow", "debug"]

[dependencies.iced_aw]
git = "https://github.com/iced-rs/iced_aw"
branch = "main"
default-features = false
features = ["tabs", "colors", "icons", "number_input", "pure"]

[dependencies]
iced_native = "0.5.1"
iced_futures = { version = "0.4.1", features = ["tokio"] }
serde = { version = "1.0.120", features = ["derive", "rc"] }
serde_json = "1.0.61"
anyhow = "1.0.38"
itertools = "0.10.0"
once_cell = "1.5.2"
levenshtein = "1.0.4"
dirs = "3.0.1"
image = "0.23.12"
self_update = "0.28.0"
semver = "1.0.4"
futures = "0.3.19"
reqwest = { version = "0.11.8", features = ["rustls-tls"] }
bytes = "1.1.0"
tempfile = "3.2.0"
tokio = { version = "1.15.0", features = ["time"] }

#tokio = { version = "1.0.2", features = ["full"] }
#futures = "0.3.12"
#reqwest = "0.11.0"
#select = "0.6.0-alpha.1"

[profile.dev]
opt-level = 2

[profile.release]
#strip = true
#lto = "fat"
