[package]
name = "spells"
version = "0.1.0"
authors = ["Andrew-Schwartz <andrewschwartz59@gmail.com>"]
edition = "2018"

[dependencies]
iced = "0.2.0"
iced_native = "0.3.0"
serde = { version = "1.0.120", features = ["derive", "rc"] }
serde_json = "1.0.61"
anyhow = "1.0.38"
itertools = "0.10.0"
once_cell = "1.5.2"
levenshtein = "1.0.4"
dirs = "3.0.1"
image = "0.23.12"

#tokio = { version = "1.0.2", features = ["full"] }
#futures = "0.3.12"
#reqwest = "0.11.0"
#select = "0.6.0-alpha.1"

[profile.dev]
opt-level = 2

[profile.release]
#lto = "fat"